// AUTO-GENERATED by scripts/build-poem-chunks.cjs
// 手动修正：实际 chunk id 范围不连续，不能用固定公式

export const CHUNK_SIZE = 100
export const CHUNK_COUNT = 21

/**
 * 根据诗 id 算出所属 chunk 索引（使用实际范围检测，不依赖连续 id 假设）
 *
 * 实际 chunk id 范围（源数据有间隔）：
 *   chunk-0:  1-100 / chunk-1:  101-200 / chunk-2:  201-300
 *   chunk-3:  301-432 / chunk-4:  433-560 / chunk-5:  561-669
 *   chunk-6:  670-769 / chunk-7:  770-869 / chunk-8:  870-969
 *   chunk-9:  970-1198 / chunk-10: 1199-1298 / chunk-11: 1299-1398
 *   chunk-12: 1399-1498 / chunk-13: 1499-1598 / chunk-14: 1599-1698
 *   chunk-15: 1699-1799 / chunk-16: 1800-1899 / chunk-17: 1900-1999
 *   chunk-18: 2000-2099 / chunk-19: 2100-2199 / chunk-20: 2200-2225
 */
const CHUNK_RANGES: [number, number, number][] = [
  [1, 100, 0], [101, 200, 1], [201, 300, 2],
  [301, 432, 3], [433, 560, 4], [561, 669, 5],
  [670, 769, 6], [770, 869, 7], [870, 969, 8],
  [970, 1198, 9], [1199, 1298, 10], [1299, 1398, 11],
  [1399, 1498, 12], [1499, 1598, 13], [1599, 1698, 14],
  [1699, 1799, 15], [1800, 1899, 16], [1900, 1999, 17],
  [2000, 2099, 18], [2100, 2199, 19], [2200, 2225, 20],
]

export function getChunkIndexForPoemId(id: number): number {
  if (id < 1) return 0
  for (const [minId, maxId, idx] of CHUNK_RANGES) {
    if (id >= minId && id <= maxId) return idx
  }
  // id 超出 2225（理论上不会发生，2028 首 id 最大 2225）
  if (id > 2225) return 20
  return 0
}
