// AUTO-GENERATED by scripts/build-poem-chunks.cjs

export const CHUNK_SIZE = 100
export const CHUNK_COUNT = 21

/** 根据诗 id 算出所属 chunk 索引 */
export function getChunkIndexForPoemId(id: number): number {
  if (id < 1) return 0
  return Math.min(CHUNK_COUNT - 1, Math.floor((id - 1) / CHUNK_SIZE))
}
